/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import code.loanCode;
import database.db;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author M_Samly
 */
public class loanList extends javax.swing.JInternalFrame {

    /**
     * Creates new form Loan
     */
    public loanList() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);

        show_Loan();
    }

    public ArrayList<loanCode> loanList() {
        ArrayList<loanCode> loanList = new ArrayList<>();
        try {
            Connection con;
            Statement st;
            con = db.getConnection();
            st = con.createStatement();
            String query = "Select * from loan order by b_id";
            ResultSet rs = st.executeQuery(query);
            loanCode pro;
            while (rs.next()) {
                pro = new loanCode(rs.getInt("b_id"), rs.getString("date"), rs.getString("time"), rs.getString("customer"), rs.getInt("telephone"), rs.getString("nic"), rs.getString("status"), rs.getFloat("amount"));
                loanList.add(pro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return loanList;
    }

    public void show_Loan() {
        ArrayList<loanCode> list = loanList();
        DefaultTableModel model = (DefaultTableModel) tblLoan.getModel();
        Object[] row = new Object[8];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getB_id();
            row[1] = list.get(i).getDate();
            row[2] = list.get(i).getTime();
            row[3] = list.get(i).getCustomer();
            row[4] = list.get(i).getTelephone();
            row[5] = list.get(i).getNic();
            row[6] = list.get(i).getStatus();
            row[7] = list.get(i).getAmount();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearchBillNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSearchName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtbill = new javax.swing.JLabel();
        txtcustomer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpayed = new javax.swing.JTextField();
        txtamount = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 712));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill No", "Date", "Time", "Customer", "Telephone", "NIC", "Status", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoan.getTableHeader().setReorderingAllowed(false);
        tblLoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoanMouseClicked(evt);
            }
        });
        tblLoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblLoanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblLoanKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoan);
        if (tblLoan.getColumnModel().getColumnCount() > 0) {
            tblLoan.getColumnModel().getColumn(0).setResizable(false);
            tblLoan.getColumnModel().getColumn(1).setResizable(false);
            tblLoan.getColumnModel().getColumn(2).setResizable(false);
            tblLoan.getColumnModel().getColumn(3).setResizable(false);
            tblLoan.getColumnModel().getColumn(4).setResizable(false);
            tblLoan.getColumnModel().getColumn(5).setResizable(false);
            tblLoan.getColumnModel().getColumn(6).setResizable(false);
            tblLoan.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 107, 730, 560));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Search By Bill No");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));

        txtSearchBillNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSearchBillNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchBillNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBillNoKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearchBillNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Search By Customer");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 170, -1));

        txtSearchName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSearchName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Bill No");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, 20));

        txtbill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(txtbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 140, 20));

        txtcustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(txtcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 140, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Customer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Payed");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, -1, 20));

        txtbalance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(txtbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, 140, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Amount");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, -1, 20));

        txtpayed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtpayed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpayedKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpayedKeyReleased(evt);
            }
        });
        jPanel1.add(txtpayed, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 130, -1));

        txtamount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 140, 20));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Loan List");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1020, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchBillNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBillNoKeyReleased
        // TODO add your handling code here:
        ArrayList<loanCode> al = new ArrayList<loanCode>();
        //al = new ArrayList<AddItems>();
        String val = txtSearchBillNo.getText().toString().trim();
        try {
            Connection con;
            Statement st;
            con = db.getConnection();
            st = con.createStatement();
            String query = "Select * from loan where b_id like '" + val + "%'";
            ResultSet rs = st.executeQuery(query);
            loanCode pro;
            while (rs.next()) {
                pro = new loanCode(rs.getInt("b_id"), rs.getString("date"), rs.getString("time"), rs.getString("customer"), rs.getInt("telephone"), rs.getString("nic"), rs.getString("status"), rs.getFloat("amount"));
                al.add(pro);
            }

            DefaultTableModel model = (DefaultTableModel) tblLoan.getModel();
            model.setRowCount(0);
            Object[] row = new Object[8];
            for (int i = 0; i < al.size(); i++) {
                row[0] = al.get(i).getB_id();
                row[1] = al.get(i).getDate();
                row[2] = al.get(i).getTime();
                row[3] = al.get(i).getCustomer();
                row[4] = al.get(i).getTelephone();
                row[5] = al.get(i).getNic();
                row[6] = al.get(i).getStatus();
                row[7] = al.get(i).getAmount();
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cannot find Item Name", "Search Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSearchBillNoKeyReleased

    private void txtSearchNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchNameKeyReleased
        // TODO add your handling code here:
        ArrayList<loanCode> al = new ArrayList<loanCode>();
        //al = new ArrayList<AddItems>();
        String val = txtSearchName.getText().toString().trim();
        try {
            Connection con;
            Statement st;
            con = db.getConnection();
            st = con.createStatement();
            String query = "Select * from loan where customer like '" + val + "%'";
            ResultSet rs = st.executeQuery(query);
            loanCode pro;
            while (rs.next()) {
                pro = new loanCode(rs.getInt("b_id"), rs.getString("date"), rs.getString("time"), rs.getString("customer"), rs.getInt("telephone"), rs.getString("nic"), rs.getString("status"), rs.getFloat("amount"));
                al.add(pro);
            }

            DefaultTableModel model = (DefaultTableModel) tblLoan.getModel();
            model.setRowCount(0);
            Object[] row = new Object[8];
            for (int i = 0; i < al.size(); i++) {
                row[0] = al.get(i).getB_id();
                row[1] = al.get(i).getDate();
                row[2] = al.get(i).getTime();
                row[3] = al.get(i).getCustomer();
                row[4] = al.get(i).getTelephone();
                row[5] = al.get(i).getNic();
                row[6] = al.get(i).getStatus();
                row[7] = al.get(i).getAmount();
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cannot find Item Name", "Search Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSearchNameKeyReleased

    private void tblLoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoanMouseClicked
        // TODO add your handling code here:
        int i = tblLoan.getSelectedRow();
        TableModel model = tblLoan.getModel();
        txtbill.setText(model.getValueAt(i, 0).toString());
        txtcustomer.setText(model.getValueAt(i, 3).toString());
        txtamount.setText(model.getValueAt(i, 7).toString());
        txtpayed.requestFocus();
    }//GEN-LAST:event_tblLoanMouseClicked

    private void txtSearchBillNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBillNoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tblLoan.requestFocus();
            tblLoan.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_txtSearchBillNoKeyPressed

    private void txtSearchNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tblLoan.requestFocus();
            tblLoan.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_txtSearchNameKeyPressed

    private void tblLoanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLoanKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            int i = tblLoan.getSelectedRow();
            TableModel model = tblLoan.getModel();
            txtbill.setText(model.getValueAt(i, 0).toString());
            txtcustomer.setText(model.getValueAt(i, 3).toString());
            txtamount.setText(model.getValueAt(i, 7).toString());
        }
    }//GEN-LAST:event_tblLoanKeyReleased

    private void tblLoanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLoanKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int i = tblLoan.getSelectedRow();
            TableModel model = tblLoan.getModel();
            txtbill.setText(model.getValueAt(i, 0).toString());
            txtcustomer.setText(model.getValueAt(i, 3).toString());
            txtamount.setText(model.getValueAt(i, 7).toString());
            txtpayed.requestFocus();
        }
    }//GEN-LAST:event_tblLoanKeyPressed

    private void txtpayedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayedKeyReleased
        // TODO add your handling code here:
        float amount = Float.parseFloat(txtamount.getText());
        float payed = Float.parseFloat(txtpayed.getText());
        float balance = amount - payed;
        txtbalance.setText(String.valueOf(new DecimalFormat("0.00").format(balance)));
    }//GEN-LAST:event_txtpayedKeyReleased

    private void txtpayedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayedKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            float payed = Float.parseFloat(txtpayed.getText());
            float balance = Float.parseFloat(txtbalance.getText());
            int billno = Integer.parseInt(txtbill.getText());
            try {
                Connection con;
                PreparedStatement pst;
                con = db.getConnection();
                String query = "Update sales set payment = payment + " + payed + ", balance = balance + " + payed + " where b_id = " + billno + "";
                pst = con.prepareStatement(query);
                pst.executeUpdate();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            if (balance == 0) {
                try {
                    Connection con;
                    PreparedStatement pst;
                    con = db.getConnection();
                    String query = "delete from loan where b_id = " + billno + "";
                    pst = con.prepareStatement(query);
                    pst.executeUpdate();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            } else {
                try {
                    Connection con;
                    PreparedStatement pst;
                    con = db.getConnection();
                    String query = "Update loan set amount = amount - " + payed + " where b_id = " + billno + "";
                    pst = con.prepareStatement(query);
                    pst.executeUpdate();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }

            DefaultTableModel model = (DefaultTableModel) tblLoan.getModel();
            model.setRowCount(0);
            show_Loan();

            txtSearchBillNo.setText(null);
            txtSearchName.setText(null);
            txtbill.setText(null);
            txtcustomer.setText(null);
            txtamount.setText(null);
            txtpayed.setText(null);
            txtbalance.setText(null);
            txtSearchBillNo.requestFocus();
        }
    }//GEN-LAST:event_txtpayedKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLoan;
    public static javax.swing.JTextField txtSearchBillNo;
    private javax.swing.JTextField txtSearchName;
    private javax.swing.JLabel txtamount;
    private javax.swing.JLabel txtbalance;
    private javax.swing.JLabel txtbill;
    private javax.swing.JLabel txtcustomer;
    private javax.swing.JTextField txtpayed;
    // End of variables declaration//GEN-END:variables
}
