/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import code.reportCode;
import database.db;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author M_Samly
 */
public class reBill extends javax.swing.JInternalFrame {

    /**
     * Creates new form report
     */
    public reBill() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);

        show_Report();
    }

    public ArrayList<reportCode> reportList() {
        ArrayList<reportCode> reportList = new ArrayList<>();
        try {
            Connection con;
            Statement st;
            con = db.getConnection();
            st = con.createStatement();
            String query = "Select * from sales where date = CURDATE() order by b_id";
            ResultSet rs = st.executeQuery(query);
            reportCode pro;
            while (rs.next()) {
                pro = new reportCode(rs.getInt("b_id"), rs.getString("cashier"), rs.getString("date"), rs.getString("time"), rs.getInt("item"), rs.getString("customer"), rs.getString("type"), rs.getFloat("total"), rs.getFloat("discount"), rs.getFloat("payment"), rs.getFloat("balance"));
                reportList.add(pro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return reportList;
    }

    public void show_Report() {
        ArrayList<reportCode> al = reportList();
        DefaultTableModel model = (DefaultTableModel) tblreBill.getModel();
        Object[] row = new Object[11];
        for (int i = 0; i < al.size(); i++) {
            row[0] = al.get(i).getBilno();
            row[1] = al.get(i).getCashier();
            row[2] = al.get(i).getDate();
            row[3] = al.get(i).getTime();
            row[4] = al.get(i).getItem();
            row[5] = al.get(i).getCustomer();
            row[6] = al.get(i).getType();
            row[7] = al.get(i).getTotal();
            row[8] = al.get(i).getDiscount();
            row[9] = al.get(i).getPayment();
            row[10] = al.get(i).getBalance();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblreBill = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtsearchbybillno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 712));

        jPanel4.setPreferredSize(new java.awt.Dimension(1024, 662));

        tblreBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill #", "Cashier", "Date", "Time", "Item", "Customer", "Type", "Total", "Discount", "Payment", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblreBill.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblreBill);
        if (tblreBill.getColumnModel().getColumnCount() > 0) {
            tblreBill.getColumnModel().getColumn(0).setResizable(false);
            tblreBill.getColumnModel().getColumn(1).setResizable(false);
            tblreBill.getColumnModel().getColumn(2).setResizable(false);
            tblreBill.getColumnModel().getColumn(3).setResizable(false);
            tblreBill.getColumnModel().getColumn(4).setResizable(false);
            tblreBill.getColumnModel().getColumn(5).setResizable(false);
            tblreBill.getColumnModel().getColumn(6).setResizable(false);
            tblreBill.getColumnModel().getColumn(7).setResizable(false);
            tblreBill.getColumnModel().getColumn(8).setResizable(false);
            tblreBill.getColumnModel().getColumn(9).setResizable(false);
            tblreBill.getColumnModel().getColumn(10).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Search By Bill No.");

        txtsearchbybillno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtsearchbybillno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchbybillnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchbybillnoKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtsearchbybillno, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsearchbybillno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchbybillnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchbybillnoKeyReleased
        // TODO add your handling code here:
        ArrayList<reportCode> al = new ArrayList<reportCode>();
        //al = new ArrayList<AddItems>();
        String val = txtsearchbybillno.getText().toString().trim();
        try {
            Connection con;
            Statement st;
            con = db.getConnection();
            st = con.createStatement();
            String query = "Select * from sales where b_id like '" + val + "%' AND date = CURDATE()";
            ResultSet rs = st.executeQuery(query);
            reportCode pro;
            while (rs.next()) {
                pro = new reportCode(rs.getInt("b_id"), rs.getString("cashier"), rs.getString("date"), rs.getString("time"), rs.getInt("item"), rs.getString("customer"), rs.getString("type"), rs.getFloat("total"), rs.getFloat("discount"), rs.getFloat("payment"), rs.getFloat("balance"));
                al.add(pro);
            }

            DefaultTableModel model = (DefaultTableModel) tblreBill.getModel();
            model.setRowCount(0);
            Object[] row = new Object[11];
            for (int i = 0; i < al.size(); i++) {
                row[0] = al.get(i).getBilno();
                row[1] = al.get(i).getCashier();
                row[2] = al.get(i).getDate();
                row[3] = al.get(i).getTime();
                row[4] = al.get(i).getItem();
                row[5] = al.get(i).getCustomer();
                row[6] = al.get(i).getType();
                row[7] = al.get(i).getTotal();
                row[8] = al.get(i).getDiscount();
                row[9] = al.get(i).getPayment();
                row[10] = al.get(i).getBalance();
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cannot find Item Name", "Search Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtsearchbybillnoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        tblreBill.setRowSelectionInterval(0, 0);
        DefaultTableModel model = (DefaultTableModel) tblreBill.getModel();
        int YesORNo = JOptionPane.showConfirmDialog(null, "Are you print bill?", "Bill Print", JOptionPane.YES_NO_OPTION);
        if (YesORNo == 0) {
            int billno = Integer.parseInt(model.getValueAt(0, 0).toString());
            try {
                Connection con;
                PreparedStatement pst, pst1, pst2, pst3, pst4, pst5;
                con = db.getConnection();
                HashMap m = new HashMap();
                m.put("Invoiceno", (billno));
                try {
                    JasperDesign jdesing = JRXmlLoader.load("E:\\M.Samly\\Clothing Management System\\Cloth_System\\src\\print\\reciept.jrxml");
                    JasperReport ireport = JasperCompileManager.compileReport(jdesing);
                    JasperPrint jprint = JasperFillManager.fillReport(ireport, m, con);
                    //JasperViewer.viewReport(jprint);
                    JasperPrintManager.printReport(jprint, false);
                    model.setRowCount(0);
                    show_Report();
                    txtsearchbybillno.setText(null);
                    txtsearchbybillno.requestFocus();
                } catch (JRException ex) {
                    Logger.getLogger(cashier.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            model.setRowCount(0);
            show_Report();
            txtsearchbybillno.setText(null);
            txtsearchbybillno.requestFocus();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsearchbybillnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchbybillnoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tblreBill.setRowSelectionInterval(0, 0);
            DefaultTableModel model = (DefaultTableModel) tblreBill.getModel();
            int YesORNo = JOptionPane.showConfirmDialog(null, "Are you print bill?", "Bill Print", JOptionPane.YES_NO_OPTION);
            if (YesORNo == 0) {
                int billno = Integer.parseInt(model.getValueAt(0, 0).toString());
                try {
                    Connection con;
                    PreparedStatement pst, pst1, pst2, pst3, pst4, pst5;
                    con = db.getConnection();
                    HashMap m = new HashMap();
                    m.put("Invoiceno", (billno));
                    try {
                        String jrmxl = "";
                        try {
                            Statement st = con.createStatement();
                            String query = "Select jrxml from shop_details where sh_id = 1";
                            ResultSet rs = st.executeQuery(query);
                            while (rs.next()) {
                                jrmxl = rs.getString("jrxml");
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                        JasperDesign jdesing = JRXmlLoader.load(jrmxl + "\\reciept.jrxml");
                        JasperReport ireport = JasperCompileManager.compileReport(jdesing);
                        JasperPrint jprint = JasperFillManager.fillReport(ireport, m, con);
                        //JasperViewer.viewReport(jprint);
                        JasperPrintManager.printReport(jprint, false);
                        model.setRowCount(0);
                        show_Report();
                        txtsearchbybillno.setText(null);
                        txtsearchbybillno.requestFocus();
                    } catch (JRException ex) {
                        Logger.getLogger(cashier.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            } else {
                model.setRowCount(0);
                show_Report();
                txtsearchbybillno.setText(null);
                txtsearchbybillno.requestFocus();
            }
        }
    }//GEN-LAST:event_txtsearchbybillnoKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblreBill;
    public static javax.swing.JTextField txtsearchbybillno;
    // End of variables declaration//GEN-END:variables
}
