/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import database.db;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author M_Samly
 */
public class returnCashier extends javax.swing.JInternalFrame {

    /**
     * Creates new form productCode
     */
    public returnCashier() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);

        Bill();
    }

    public void Bill() {
        try {
            Connection con;
            Statement st;
            con = db.getConnection();
            st = con.createStatement();
            String query = "Select b_id from bill_no"; //order by Name";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                int bill = rs.getInt("b_id");
                txtBillNo.setText(Integer.toString(bill));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        txtSearchBarcode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JLabel();
        txtType = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        txtCustomer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPayment = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotalDiscount = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtItem = new javax.swing.JLabel();
        txtBillNo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 712));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        txtSearchBarcode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchBarcodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBarcodeKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Search By Barcode");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("F1 - Retail");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("F2 - Wholesale");

        txtUserName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUserName.setText("-");

        txtType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtType.setText("Retail");

        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Name", "Price", "Quantity", "Discount", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBill.getTableHeader().setReorderingAllowed(false);
        tblBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBillMouseClicked(evt);
            }
        });
        tblBill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblBillKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblBill);
        if (tblBill.getColumnModel().getColumnCount() > 0) {
            tblBill.getColumnModel().getColumn(0).setResizable(false);
            tblBill.getColumnModel().getColumn(1).setResizable(false);
            tblBill.getColumnModel().getColumn(2).setResizable(false);
            tblBill.getColumnModel().getColumn(3).setResizable(false);
            tblBill.getColumnModel().getColumn(4).setResizable(false);
            tblBill.getColumnModel().getColumn(5).setResizable(false);
        }

        txtCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCustomer.setText("Customer");
        txtCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomerKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Reset All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Total");

        txtTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTotalAmount.setText("0.00");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Payment");

        txtPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPaymentKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Discount");

        txtTotalDiscount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTotalDiscount.setText("0.00");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Item");

        txtItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtItem.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalDiscount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        txtBillNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtBillNo.setText("0");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("E - Edit");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("D - Discount");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DELETE - Delete");

        jButton11.setText("Re Bill");
        jButton11.setPreferredSize(new java.awt.Dimension(75, 75));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(txtSearchBarcode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtUserName)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSearchBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBillNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(11, 11, 11)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchBarcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBarcodeKeyReleased
        // TODO add your handling code here:
        String type = txtType.getText();
        if (type == "Retail") {
            /*ArrayList<cashierCode> al = new ArrayList<cashierCode>();
            //al = new ArrayList<AddItems>();
            String val = txtSearchBarcode.getText().toString().trim();
            try {
                Connection con;
                Statement st;
                con = db.getConnection();
                st = con.createStatement();
                String query = "Select * from product where quantity > 0 AND barcode like '" + val + "%'";
                ResultSet rs = st.executeQuery(query);
                cashierCode pro;
                while (rs.next()) {
                    pro = new cashierCode(rs.getString("barcode"), rs.getString("name"), rs.getInt("quantity"), rs.getFloat("rprice"));
                    al.add(pro);
                }

                DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
                model.setRowCount(0);
                Object[] row = new Object[6];
                for (int i = 0; i < al.size(); i++) {
                    row[0] = al.get(i).getBarcode();
                    row[1] = al.get(i).getName();
                    row[2] = al.get(i).getQty();
                    row[3] = al.get(i).getPrice();
                    model.addRow(row);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Cannot find Item Name", "Search Error", JOptionPane.ERROR_MESSAGE);
            }*/

 /* try {
                String searchBarcode = txtSearchBarcode.getText();
                Connection con;
                Statement st;
                con = db.getConnection();
                st = con.createStatement();
                String query = "Select barcode,name,rprice From product where barcode = '" + txtSearchBarcode.getText() + "'";
                PreparedStatement pst = con.prepareStatement(query);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    String barcode = rs.getString("barcode");
                    String name = rs.getString("name");
                    float rprice = rs.getFloat("rprice");
                    //System.out.println(barcode);
                    if (searchBarcode == barcode) {
                        txtName.setText(name);
                        txtPrice.setText(String.valueOf(new DecimalFormat("0.00").format(rprice)));
                    }
                }
             */
 /*
                
                 int j = 0;
                //txtOk.requestFocus();
                DefaultTableModel model = new DefaultTableModel();
                model = (DefaultTableModel) tblBill.getModel();
                model.addRow(new Object[]{
                    txtBarcode.getText(),
                    txtName.getText(),
                    txtPrice.getText(),
                    txtQty.getText(),
                    txtDiscount.getText(),
                    txtTotal.getText(),}
                );

                float sum = 0;
                float discounttot = 0;
                for (int i = 0; i < tblBill.getRowCount(); i++) {
                    discounttot = discounttot + Float.parseFloat(tblBill.getValueAt(i, 4).toString());//* (Double.parseDouble(jTableBill.getValueAt(i, 1).toString()) * Double.parseDouble(jTableBill.getValueAt(i, 2).toString())
                    sum = sum + Float.parseFloat(tblBill.getValueAt(i, 5).toString());// - Double.parseDouble(tblBill.getValueAt(i, 4).toString());
                    j = i + 1;
                }
                float returnamount = Float.parseFloat(txtReturn.getText());
                float finalsum = sum - returnamount;
                txtItem.setText(Integer.toString(j));
                txtTotalAmount.setText(String.valueOf(new DecimalFormat("0.00").format(finalsum)));
                txtTotalDiscount.setText(String.valueOf(new DecimalFormat("0.00").format(discounttot)));

                
             */
            //txtQty.requestFocus();
            /* } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);//"Cannot find Item Name", "Search Error", JOptionPane.ERROR_MESSAGE);
            }*/
        } else if (type == "Wholesale") {
            /*ArrayList<cashierCode> al = new ArrayList<cashierCode>();
            //al = new ArrayList<AddItems>();
            String val = txtSearchBarcode.getText().toString().trim();
            try {
                Connection con;
                Statement st;
                con = db.getConnection();
                st = con.createStatement();
                String query = "Select * from product where quantity > 0 AND barcode like '" + val + "%'";
                ResultSet rs = st.executeQuery(query);
                cashierCode pro;
                while (rs.next()) {
                    pro = new cashierCode(rs.getString("barcode"), rs.getString("name"), rs.getInt("quantity"), rs.getFloat("wprice"));
                    al.add(pro);
                }

                DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
                model.setRowCount(0);
                Object[] row = new Object[6];
                for (int i = 0; i < al.size(); i++) {
                    row[0] = al.get(i).getBarcode();
                    row[1] = al.get(i).getName();
                    row[2] = al.get(i).getQty();
                    row[3] = al.get(i).getPrice();
                    model.addRow(row);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Cannot find Item Name", "Search Error", JOptionPane.ERROR_MESSAGE);
            }*/
        }
        /*String barcode = txtSearchBarcode.getText();
        DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
        String barcodeModal = model.getValueAt(0, 0).toString();
        if (barcodeModal.equalsIgnoreCase(barcode)) {
            txtQty.requestFocus();
        }*/

    }//GEN-LAST:event_txtSearchBarcodeKeyReleased

    private void txtSearchBarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBarcodeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            txtType.setText("Retail");
        } else if (evt.getKeyCode() == KeyEvent.VK_F2) {
            txtType.setText("Wholesale");
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            txtPayment.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //tblProduct.requestFocus();
            //tblProduct.setRowSelectionInterval(0, 0);

            /*else {
            String barcode = txtSearchBarcode.getText();
            DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                String barcodeModal = model.getValueAt(i, 0).toString();
                if(barcode.equalsIgnoreCase(barcodeModal)){
                    txtQty.requestFocus();
                }
            }
        }*/
            String barcode = "";
            String name = "";
            float rprice = 0;
            boolean sameProduct = false;
            boolean status = false;
            int rowNumber = 0;
            int j = 0;

            String type = txtType.getText();

            try {
                Connection con;
                Statement st;
                con = db.getConnection();
                st = con.createStatement();

                String query = "Select barcode,name,rprice,wprice From product where barcode = '" + txtSearchBarcode.getText() + "'";
                PreparedStatement pst = con.prepareStatement(query);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    barcode = rs.getString("barcode");
                    name = rs.getString("name");
                    if (type == "Retail") {
                        rprice = rs.getFloat("rprice");
                    } else {
                        rprice = rs.getFloat("wprice");
                    }
                    String searchBarcode = txtSearchBarcode.getText();
                    if (searchBarcode.equals(barcode)) {
                        sameProduct = true;
                    }
                }

                if (sameProduct == true) {
                    //txtOk.requestFocus();
                    DefaultTableModel model = new DefaultTableModel();
                    model = (DefaultTableModel) tblBill.getModel();
                    if (model.getRowCount() == 0) {
                        model.addRow(new Object[]{
                            barcode,
                            name,
                            rprice,
                            1,
                            0.00,
                            rprice,}
                        );
                    } else {
                        for (int i = 0; i < model.getRowCount(); i++) {
                            String tableBarcode = model.getValueAt(i, 0).toString();
                            if (barcode.equals(tableBarcode)) {
                                status = true;
                                rowNumber = i;
                            }
                        }
                        if (status == true) {
                            int qunatity = Integer.parseInt(model.getValueAt(rowNumber, 3).toString()) + 1;
                            model.setValueAt(qunatity, rowNumber, 3);
                            float price = Float.parseFloat(model.getValueAt(rowNumber, 5).toString()) + rprice;
                            model.setValueAt(price, rowNumber, 5);

                            status = false;
                            rowNumber = 0;
                        } else {
                            model.addRow(new Object[]{
                                barcode,
                                name,
                                rprice,
                                1,
                                0.00,
                                rprice,}
                            );
                        }
                    }

                    sameProduct = false;
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Barcode");
                }

                barcode = "";
                name = "";
                rprice = 0;
                sameProduct = true;
                status = false;
                rowNumber = 0;

                txtSearchBarcode.setText(null);
                txtSearchBarcode.requestFocus();

                float sum = 0;
                float discounttot = 0;
                int item = 0;
                for (int i = 0; i < tblBill.getRowCount(); i++) {
                    discounttot = discounttot + Float.parseFloat(tblBill.getValueAt(i, 4).toString());//* (Double.parseDouble(jTableBill.getValueAt(i, 1).toString()) * Double.parseDouble(jTableBill.getValueAt(i, 2).toString())
                    sum = sum + Float.parseFloat(tblBill.getValueAt(i, 5).toString());// - Double.parseDouble(tblBill.getValueAt(i, 4).toString());
                    item = Integer.parseInt(tblBill.getValueAt(i, 3).toString());
                    j = j + item;
                }
                float finalsum = sum;
                txtItem.setText(Integer.toString(j));
                txtTotalAmount.setText(String.valueOf(new DecimalFormat("0.00").format(finalsum)));
                txtTotalDiscount.setText(String.valueOf(new DecimalFormat("0.00").format(discounttot)));
                txtPayment.setText(String.valueOf(new DecimalFormat("0.00").format(finalsum)));

                //txtQty.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);//"Cannot find Item Name", "Search Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtSearchBarcodeKeyPressed

    private void txtCustomerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPayment.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            txtSearchBarcode.requestFocus();
        }
    }//GEN-LAST:event_txtCustomerKeyPressed

    private void txtPaymentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaymentKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            txtTotalDiscount.setText(String.valueOf(new DecimalFormat("0.00").format(Float.parseFloat(txtTotalDiscount.getText()))));
            float checkpayment = Float.parseFloat(txtPayment.getText());
            if (checkpayment == 0) {
                int YesORNo = JOptionPane.showConfirmDialog(null, "Do you want to continue?", "Warning Option", JOptionPane.YES_NO_OPTION);
                if (YesORNo == 0) {
                    sales();
                    billPrint();

                    txtItem.setText("0");
                    txtCustomer.setText("Customer");
                    txtTotalDiscount.setText("0.00");
                    txtTotalAmount.setText("0.00");
                    txtPayment.setText(null);

                    DefaultTableModel model = (DefaultTableModel) tblBill.getModel();
                    model.setRowCount(0);

                } else {
                    txtPayment.requestFocus();
                }

            } else {
                sales();
                billPrint();

                txtItem.setText("0");
                txtCustomer.setText("Customer");
                txtTotalDiscount.setText("0.00");
                txtTotalAmount.setText("0.00");
                txtPayment.setText(null);

                DefaultTableModel model = (DefaultTableModel) tblBill.getModel();
                model.setRowCount(0);

            }
            this.dispose();
            cashier.txtSearchBarcode.requestFocus();

            try {
                Connection con;
                Statement st;
                con = db.getConnection();
                st = con.createStatement();
                String query = "Select b_id from bill_no"; //order by Name";
                PreparedStatement pst = con.prepareStatement(query);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    int bill = rs.getInt("b_id");
                    cashier.txtBillNo.setText(Integer.toString(bill));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            txtSearchBarcode.requestFocus();
        }
    }//GEN-LAST:event_txtPaymentKeyPressed

    private void tblBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBillMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBillMouseClicked

    private void tblBillKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblBillKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            int k = tblBill.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tblBill.getModel();
            model.removeRow(k);

            int j = 0;
            float sum = 0;
            float discounttot = 0;
            int item = 0;
            for (int i = 0; i < tblBill.getRowCount(); i++) {
                discounttot = discounttot + Float.parseFloat(tblBill.getValueAt(i, 4).toString());//* (Double.parseDouble(jTableBill.getValueAt(i, 1).toString()) * Double.parseDouble(jTableBill.getValueAt(i, 2).toString())
                sum = sum + Float.parseFloat(tblBill.getValueAt(i, 5).toString());// - Double.parseDouble(tblBill.getValueAt(i, 4).toString());
                item = Integer.parseInt(tblBill.getValueAt(i, 3).toString());
                j = j + item;
            }
            float finalsum = sum;
            txtItem.setText(Integer.toString(j));
            txtTotalAmount.setText(String.valueOf(new DecimalFormat("0.00").format(finalsum)));
            txtTotalDiscount.setText(String.valueOf(new DecimalFormat("0.00").format(discounttot)));
            txtSearchBarcode.requestFocus();

        } else if (evt.getKeyCode() == KeyEvent.VK_E) {
            editCashier edtCash = new editCashier();
            int i = tblBill.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tblBill.getModel();
            edtCash.txtBarcode.setText(model.getValueAt(i, 0).toString());
            edtCash.txtName.setText(model.getValueAt(i, 1).toString());
            edtCash.txtPrice.setText(model.getValueAt(i, 2).toString());
            edtCash.txtQuantity.setText(model.getValueAt(i, 3).toString());
            edtCash.txtDiscount.setText(model.getValueAt(i, 4).toString());
            edtCash.txtTotal.setText(model.getValueAt(i, 5).toString());
            jDesktopPane1.add(edtCash).setVisible(true);
            editCashier.txtQuantity.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_D) {
            discountCashier disCashi = new discountCashier();
            int i = tblBill.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tblBill.getModel();
            disCashi.txtBarcode.setText(model.getValueAt(i, 0).toString());
            disCashi.txtName.setText(model.getValueAt(i, 1).toString());
            disCashi.txtPrice.setText(model.getValueAt(i, 2).toString());
            disCashi.txtQuantity.setText(model.getValueAt(i, 3).toString());
            disCashi.txtDiscount.setText(model.getValueAt(i, 4).toString());
            disCashi.txtTotal.setText(model.getValueAt(i, 5).toString());
            jDesktopPane1.add(disCashi).setVisible(true);
            disCashi.txtDiscount.requestFocus();
        }
    }//GEN-LAST:event_tblBillKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtItem.setText("0");
        txtCustomer.setText("Customer");
        txtTotalDiscount.setText("0.00");
        txtTotalAmount.setText("0.00");
        txtPayment.setText(null);

        /*        
        txtBarcode.setText(null);
        txtName.setText(null);
        txtQty.setText("0");
        txtPrice.setText(null);
        txtTotal.setText(null);
        txtDiscount.setText("0");
         */
        txtSearchBarcode.setText(null);
        txtSearchBarcode.requestFocus();

        DefaultTableModel model = (DefaultTableModel) tblBill.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void sales() {

        try {
            Connection con;
            PreparedStatement pst, pst1, pst2, pst3, pst4, pst5;
            con = db.getConnection();

            int billNo = Integer.parseInt(txtBillNo.getText());
            String cashier = txtUserName.getText();
            int item = Integer.parseInt(txtItem.getText());
            String customer = txtCustomer.getText();
            float total = Float.parseFloat(txtTotalAmount.getText());
            float discount = Float.parseFloat(txtTotalDiscount.getText());
            float payment = Float.parseFloat(txtPayment.getText());

            try {
                String query = "Insert into sales (b_id, cashier, date, time, item, customer, type, total, discount, payment, balance) values (?, ?,CURDATE(),CURTIME(),?,?,?,?,?,?,?)";
                pst = con.prepareStatement(query);
                pst.setInt(1, billNo);
                pst.setString(2, cashier);
                pst.setInt(3, item);
                pst.setString(4, customer);
                pst.setString(5, "Return");
                pst.setFloat(6, -total);
                pst.setFloat(7, -discount);
                pst.setFloat(8, -payment);
                pst.setFloat(9, 0);
                pst.executeUpdate();

                try {

                    int rows = tblBill.getRowCount();
                    String query1 = "Insert into sales_product (b_id, barcode, name, price, quantity, discount, total) values (?,?,?,?,?,?,?)";
                    pst1 = con.prepareStatement(query1);

                    String barcode = "";
                    String iName = "";
                    float iprice = 0;
                    float iqty = 0;
                    float iDis = 0;
                    float iTotal = 0;

                    for (int i = 0; i < tblBill.getRowCount(); i++) {
                        barcode = (String) tblBill.getValueAt(i, 0);
                        iName = (String) tblBill.getValueAt(i, 1);
                        iprice = (Float.parseFloat(tblBill.getValueAt(i, 2).toString()));
                        iqty = (Float.parseFloat(tblBill.getValueAt(i, 3).toString()));
                        iDis = (Float.parseFloat(tblBill.getValueAt(i, 4).toString()));
                        iTotal = (Float.parseFloat(tblBill.getValueAt(i, 5).toString()));

                        pst1.setInt(1, billNo);
                        pst1.setString(2, barcode);
                        pst1.setString(3, iName);
                        pst1.setFloat(4, iprice);
                        pst1.setFloat(5, -iqty);
                        pst1.setFloat(6, -iDis);
                        pst1.setFloat(7, -iTotal);
                        pst1.executeUpdate();

                        try {
                            String query2 = "Select bprice from product where barcode = '" + barcode + "' AND name = '" + iName + "' ";
                            pst2 = con.prepareStatement(query2);
                            ResultSet rs = pst2.executeQuery();

                            while (rs.next()) {
                                float bprice = rs.getFloat("bprice");

                                float income = iTotal - (bprice * iqty);

                                try {
                                    String query4 = "Insert into product_income (date, year, month, barcode, name, income) values (CURDATE(), YEAR(CURDATE()), MONTH(CURDATE()),?,?,?)";
                                    pst4 = con.prepareStatement(query4);
                                    pst4.setString(1, barcode);
                                    pst4.setString(2, iName);
                                    pst4.setFloat(3, -income);
                                    pst4.executeUpdate();

                                } catch (Exception e) {
                                    JOptionPane.showMessageDialog(null, e);
                                }
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                        try {
                            String query3 = "Update product set Quantity = Quantity + '" + iqty + "' where barcode = '" + barcode + "' AND name= '" + iName + "'";
                            pst3 = con.prepareStatement(query3);
                            pst3.executeUpdate();

                            String saletype = txtType.getText();
                            if (saletype == "Retail") {
                                txtType.setText("Retail");
                            } else {
                                txtType.setText("Wholesale");
                            }

                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }

                    }

                    try {
                        String query5 = "Insert into bill_no (date, time) values (CURDATE(),CURTIME())";
                        pst5 = con.prepareStatement(query5);
                        pst5.executeUpdate();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                    Bill();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void billPrint() {

        try {
            Connection con;
            PreparedStatement pst, pst1, pst2, pst3, pst4, pst5;
            con = db.getConnection();
            int bill = Integer.parseInt(txtBillNo.getText());
            HashMap m = new HashMap();
            m.put("Invoiceno", (bill - 1));
            try {
                String jrmxl = "";
                try {
                    Statement st = con.createStatement();
                    String query = "Select jrxml from shop_details where sh_id = 1";
                    ResultSet rs = st.executeQuery(query);
                    while (rs.next()) {
                        jrmxl = rs.getString("jrxml");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                JasperDesign jdesing = JRXmlLoader.load(jrmxl + "\\returnReciept.jrxml");
                JasperReport ireport = JasperCompileManager.compileReport(jdesing);
                JasperPrint jprint = JasperFillManager.fillReport(ireport, m, con);
                //JasperViewer.viewReport(jprint);
                JasperPrintManager.printReport(jprint, false);
                txtSearchBarcode.requestFocus();
            } catch (JRException ex) {
                Logger.getLogger(returnCashier.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tblBill;
    private javax.swing.JLabel txtBillNo;
    public static javax.swing.JTextField txtCustomer;
    public static javax.swing.JLabel txtItem;
    private javax.swing.JTextField txtPayment;
    public static javax.swing.JTextField txtSearchBarcode;
    public static javax.swing.JLabel txtTotalAmount;
    public static javax.swing.JLabel txtTotalDiscount;
    public static javax.swing.JLabel txtType;
    public static javax.swing.JLabel txtUserName;
    // End of variables declaration//GEN-END:variables
}
